# This is an updated config for using I3D on ActivtyNet, resulting in slightly
# better performance. To reproduce the setting in our paper, set

dataset_name: anet
train_split: ['training']
val_split: ['validation']
devices: ['cuda:0']
dataset: {
  json_file: ./data/anet_1.3/annotations/anet1.3_i3d_filtered.json,
  feat_folder: ./data/anet_1.3/i3d_features,
  mae_feat_folder: ./data/anet_1.3/anet_mae_hugek700,
  file_prefix: v_,
  file_ext: .npy,
  num_classes: 1,
  input_dim: 2048,
  feat_stride: 16,
  num_frames: 16,
  default_fps: 25,
  trunc_thresh: 0.5,
  crop_ratio: [0.9, 1.0],
  # upsample the features to a fixed length of 192
  max_seq_len: 192,
  force_upsampling: True,
  encoder_type: 'i3d',
}
model: {
  backbone_type: 'ConvFormer',
  fpn_type: identity,
  max_buffer_len_factor: 1.0,
  # 192 - 96 - 48 - 24 - 12 - 6
  backbone_arch: [ 2, 1, 5 ],
  DWConv_ks: [3,3,3,3,3,3],
  embd_dim: 256,
  fpn_dim: 256,
  head_dim: 256,
  block_mlp_dim: 1024,
  use_abs_pe: True,
  num_bins: 12,
  iou_weight_power: 1,
  input_noise: 0.5,
  MaxPool_ks: [3,3,3,3,3,3],
  LFE_lambda: 0.5,
  init_conv_vars: 0.2,
  feat_win_size: 9,
}
opt: {
  learning_rate: 0.001,
  epochs: 10,
  weight_decay: 0.05,
  gaussian_sigma: 1,
  gaussian_epoch: 10,
}
loader: {
  batch_size: 16,
}
train_cfg: {
  start_save_epoch: 6,
  init_loss_norm: 200,
  clip_grad_l2norm: 1.0,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
  label_smoothing: 0.1,
  droppath: 0.1,
}

# similar to THUMOS
test_cfg: {
  voting_thresh: 0.9,
  pre_nms_topk: 2000,
  # max of 100 predictions per video
  max_seg_num: 100,
  min_score: 0.001,
  # score fusion
  multiclass_nms: False,
  nms_sigma : 0.75,
  ext_score_file: ./data/anet_1.3/annotations/new_3ensemble_uniformerv2_large_only_global_anet_16x10x3.json,
  duration_thresh: 0.001,
}
output_folder: ./ckpt/