dataset_name: multithumos
train_split: [ 'validation' ]
val_split: [ 'test' ]
devices: ['cuda:0']
dataset: {
  json_file: ./data/thumos/annotations/multithumos.json,
  i3d_feat_folder: ./data/thumos/i3d_features,
  videomaev2_feat_folder: ./data/thumos/th14_mae_g_16_4,
  file_prefix: ~,
  file_ext: .npy,
  num_classes: 65,
  input_dim: 2048,
  feat_stride: 4,
  num_frames: 16,
  # serve as data augmentation
  trunc_thresh: 0.5,
  crop_ratio: [ 0.9, 1.0 ],
  max_seq_len: 2304,
  encoder_type: 'i3d',
}
model: {
  backbone_type: 'ConvFormer',
  fpn_type: identity, # identity / fpn / fan
  max_buffer_len_factor: 6.0,
  backbone_arch: [ 2, 0, 5 ],
  DWConv_ks: [1,3,3,3,3,3],
  regression_range: [ [ 0, 4 ], [ 4, 8 ], [ 8, 16 ], [ 16, 32 ], [ 32, 64 ], [ 64, 10000 ] ],
  embd_dim: 640,
  fpn_dim: 640,
  head_dim: 640,
  init_conv_vars: 0.2,
  num_bins: 16,
  iou_weight_power: 0.2,
  use_trident_head: True,
  block_mlp_dim: 2560,
  input_noise: 0.0005, 
  MaxPool_ks: [1,7,7,7,7,7],
  LFE_lambda: 0.5,
  feat_win_size: 9,
  multi_label: True,
}
opt: {
  learning_rate: 0.0001,
  warmup_epochs: 20,
  epochs: 40,
  weight_decay: 0.03,
  gaussian_sigma: 1,
  gaussian_epoch: 20,
}
loader: {
  batch_size: 2,
}
train_cfg: {
  start_save_epoch: 21,
  init_loss_norm: 100,
  clip_grad_l2norm: 1.0,
  cls_prior_prob: 0.01,
  center_sample: radius, # 'radius'/ 'none'
  center_sample_radius: 1.5,
}
# the inference on THUMOS is quite different from EPIC-kitchens
# a major performance gain is achieved by fusing external classification scores
# doing so will require disable multiclass_nms and enable score fusion
test_cfg: {
  voting_thresh: 0.7,
  pre_nms_topk: 8000,
  max_seg_num: 8000,
  min_score: 0.001,
  multiclass_nms: True,
}
output_folder: ./ckpt/
